name: coinboost
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_native_splash: 2.4.1
  http: ^1.3.0
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/g.jpg
    - assets/images/n.jpg
    - assets/images/avatar.jpeg

flutter_native_splash:
  color: "#ffffff" # Background color (change to your preferred color)
  image: assets/images/1.png # Path to the splash image
  android_12:
    color: "#ffffff" # Background color for Android 12+
    image: assets/images/1.png
