// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdsbw7X_58N-XzoBFc7FlMRwyP6Sj1ztY',
    appId: '1:173871804927:web:75d7efc26fb0f865b4f7ca',
    messagingSenderId: '173871804927',
    projectId: 'coinboost-87828',
    authDomain: 'coinboost-87828.firebaseapp.com',
    storageBucket: 'coinboost-87828.firebasestorage.app',
    measurementId: 'G-E81S19WEDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuZhLqgrM8jEklsxMD45EacBiK9FKoGWE',
    appId: '1:173871804927:android:f357c8826204d125b4f7ca',
    messagingSenderId: '173871804927',
    projectId: 'coinboost-87828',
    storageBucket: 'coinboost-87828.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4J7aSbX551eacfVJKpgM4nuUsfPzigD0',
    appId: '1:173871804927:ios:e9f08b0fcb579f86b4f7ca',
    messagingSenderId: '173871804927',
    projectId: 'coinboost-87828',
    storageBucket: 'coinboost-87828.firebasestorage.app',
    iosBundleId: 'com.example.coinboost',
  );
}
